// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomReservation.Data;

namespace RoomReservation.Data.Migrations
{
    [DbContext(typeof(RoomReservationDbContext))]
    partial class RoomReservationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RoomReservation.Data.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FromStudentId")
                        .IsRequired();

                    b.Property<string>("RoomNumber")
                        .IsRequired();

                    b.Property<string>("ToStudentId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber");

                    b.HasIndex("ToStudentId");

                    b.HasIndex("FromStudentId", "ToStudentId")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("RoomReservation.Data.Models.Room", b =>
                {
                    b.Property<string>("Number")
                        .HasMaxLength(4);

                    b.Property<string>("ApartmentRoomNumber");

                    b.Property<byte>("Capacity");

                    b.Property<string>("Comments")
                        .HasMaxLength(500);

                    b.Property<bool?>("IsMale");

                    b.Property<bool>("IsRA");

                    b.Property<bool>("IsReserved");

                    b.HasKey("Number");

                    b.HasIndex("ApartmentRoomNumber")
                        .IsUnique()
                        .HasFilter("[ApartmentRoomNumber] IS NOT NULL");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("RoomReservation.Data.Models.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(9);

                    b.Property<string>("Comments")
                        .HasMaxLength(500);

                    b.Property<byte>("CreditHours");

                    b.Property<string>("CurrentRoomNumber");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("IsMale");

                    b.Property<bool>("IsOnCampus");

                    b.Property<bool>("IsRA");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50);

                    b.Property<string>("PreviousRoomNumber");

                    b.Property<DateTime?>("RegistrationTime");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRoomNumber");

                    b.HasIndex("PreviousRoomNumber");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("RoomReservation.Data.Models.Invitation", b =>
                {
                    b.HasOne("RoomReservation.Data.Models.Student", "FromStudent")
                        .WithMany("InvitationsSent")
                        .HasForeignKey("FromStudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoomReservation.Data.Models.Room", "Room")
                        .WithMany("Invitations")
                        .HasForeignKey("RoomNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoomReservation.Data.Models.Student", "ToStudent")
                        .WithMany("InvitationsReceived")
                        .HasForeignKey("ToStudentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RoomReservation.Data.Models.Room", b =>
                {
                    b.HasOne("RoomReservation.Data.Models.Room", "ApartmentRoom")
                        .WithOne()
                        .HasForeignKey("RoomReservation.Data.Models.Room", "ApartmentRoomNumber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RoomReservation.Data.Models.Student", b =>
                {
                    b.HasOne("RoomReservation.Data.Models.Room", "CurrentRoom")
                        .WithMany("CurrentResidents")
                        .HasForeignKey("CurrentRoomNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoomReservation.Data.Models.Room", "PreviousRoom")
                        .WithMany("PreviousResidents")
                        .HasForeignKey("PreviousRoomNumber")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
